---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
  labels:
    app: agent-sandbox-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-sandbox-controller
  template:
    metadata:
      labels:
        app: agent-sandbox-controller
    spec:
      serviceAccountName: agent-sandbox-controller
      containers:
      - name: agent-sandbox-controller
        image: agent-sandbox-controller:latest
        args:
        - "--leader-elect=true"
        - "--extensions"
        - "--sandbox-concurrent-workers=1000"
        - "--sandbox-claim-concurrent-workers=1000"
        - "--sandbox-warm-pool-concurrent-workers=1000"
        - "--kube-api-qps=600"
        - "--kube-api-burst=600"
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: healthz
          containerPort: 8081
          protocol: TCP
