apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxClaim
metadata:
  name: python-claim-8
  namespace: default
spec:
  sandboxTemplateRef:
    name: sandbox-python-template-v1
  warmpool: python-pool
