// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/agents.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatingMode int32

const (
	OperatingMode_OPERATING_MODE_UNSPECIFIED OperatingMode = 0
	OperatingMode_OPERATING_MODE_RUNNING     OperatingMode = 1
	OperatingMode_OPERATING_MODE_SUSPENDED   OperatingMode = 2
)

// Enum value maps for OperatingMode.
var (
	OperatingMode_name = map[int32]string{
		0: "OPERATING_MODE_UNSPECIFIED",
		1: "OPERATING_MODE_RUNNING",
		2: "OPERATING_MODE_SUSPENDED",
	}
	OperatingMode_value = map[string]int32{
		"OPERATING_MODE_UNSPECIFIED": 0,
		"OPERATING_MODE_RUNNING":     1,
		"OPERATING_MODE_SUSPENDED":   2,
	}
)

func (x OperatingMode) Enum() *OperatingMode {
	p := new(OperatingMode)
	*p = x
	return p
}

func (x OperatingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agents_proto_enumTypes[0].Descriptor()
}

func (OperatingMode) Type() protoreflect.EnumType {
	return &file_v1_agents_proto_enumTypes[0]
}

func (x OperatingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatingMode.Descriptor instead.
func (OperatingMode) EnumDescriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{0}
}

type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNSPECIFIED  SandboxState = 0
	SandboxState_SANDBOX_STATE_PROVISIONING SandboxState = 1
	SandboxState_SANDBOX_STATE_RUNNING      SandboxState = 2
	SandboxState_SANDBOX_STATE_SUSPENDING   SandboxState = 3
	SandboxState_SANDBOX_STATE_SUSPENDED    SandboxState = 4
	SandboxState_SANDBOX_STATE_RESUMING     SandboxState = 5
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNSPECIFIED",
		1: "SANDBOX_STATE_PROVISIONING",
		2: "SANDBOX_STATE_RUNNING",
		3: "SANDBOX_STATE_SUSPENDING",
		4: "SANDBOX_STATE_SUSPENDED",
		5: "SANDBOX_STATE_RESUMING",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED":  0,
		"SANDBOX_STATE_PROVISIONING": 1,
		"SANDBOX_STATE_RUNNING":      2,
		"SANDBOX_STATE_SUSPENDING":   3,
		"SANDBOX_STATE_SUSPENDED":    4,
		"SANDBOX_STATE_RESUMING":     5,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agents_proto_enumTypes[1].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_v1_agents_proto_enumTypes[1]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{1}
}

type SuspendSandboxRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace          string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ForceSnapshot      bool                   `protobuf:"varint,3,opt,name=force_snapshot,json=forceSnapshot,proto3" json:"force_snapshot,omitempty"`
	GracePeriodSeconds int64                  `protobuf:"varint,4,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SuspendSandboxRequest) Reset() {
	*x = SuspendSandboxRequest{}
	mi := &file_v1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendSandboxRequest) ProtoMessage() {}

func (x *SuspendSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendSandboxRequest.ProtoReflect.Descriptor instead.
func (*SuspendSandboxRequest) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *SuspendSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SuspendSandboxRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SuspendSandboxRequest) GetForceSnapshot() bool {
	if x != nil {
		return x.ForceSnapshot
	}
	return false
}

func (x *SuspendSandboxRequest) GetGracePeriodSeconds() int64 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

type SuspendSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SnapshotUid   string                 `protobuf:"bytes,2,opt,name=snapshot_uid,json=snapshotUid,proto3" json:"snapshot_uid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendSandboxResponse) Reset() {
	*x = SuspendSandboxResponse{}
	mi := &file_v1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendSandboxResponse) ProtoMessage() {}

func (x *SuspendSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendSandboxResponse.ProtoReflect.Descriptor instead.
func (*SuspendSandboxResponse) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *SuspendSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SuspendSandboxResponse) GetSnapshotUid() string {
	if x != nil {
		return x.SnapshotUid
	}
	return ""
}

func (x *SuspendSandboxResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ResumeSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SnapshotUid   string                 `protobuf:"bytes,3,opt,name=snapshot_uid,json=snapshotUid,proto3" json:"snapshot_uid,omitempty"`
	PreWarmOnly   bool                   `protobuf:"varint,4,opt,name=pre_warm_only,json=preWarmOnly,proto3" json:"pre_warm_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxRequest) Reset() {
	*x = ResumeSandboxRequest{}
	mi := &file_v1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxRequest) ProtoMessage() {}

func (x *ResumeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxRequest.ProtoReflect.Descriptor instead.
func (*ResumeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeSandboxRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResumeSandboxRequest) GetSnapshotUid() string {
	if x != nil {
		return x.SnapshotUid
	}
	return ""
}

func (x *ResumeSandboxRequest) GetPreWarmOnly() bool {
	if x != nil {
		return x.PreWarmOnly
	}
	return false
}

type ResumeSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PodIp         string                 `protobuf:"bytes,2,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxResponse) Reset() {
	*x = ResumeSandboxResponse{}
	mi := &file_v1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxResponse) ProtoMessage() {}

func (x *ResumeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxResponse.ProtoReflect.Descriptor instead.
func (*ResumeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeSandboxResponse) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *ResumeSandboxResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetSandboxStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusRequest) Reset() {
	*x = GetSandboxStatusRequest{}
	mi := &file_v1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusRequest) ProtoMessage() {}

func (x *GetSandboxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{4}
}

func (x *GetSandboxStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSandboxStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Condition struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Type                      string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status                    string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason                    string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message                   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionTimeEpochMs int64                  `protobuf:"varint,5,opt,name=last_transition_time_epoch_ms,json=lastTransitionTimeEpochMs,proto3" json:"last_transition_time_epoch_ms,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_v1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{5}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Condition) GetLastTransitionTimeEpochMs() int64 {
	if x != nil {
		return x.LastTransitionTimeEpochMs
	}
	return 0
}

type GetSandboxStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         SandboxState           `protobuf:"varint,2,opt,name=state,proto3,enum=agents.integration.v1.SandboxState" json:"state,omitempty"`
	DesiredMode   OperatingMode          `protobuf:"varint,3,opt,name=desired_mode,json=desiredMode,proto3,enum=agents.integration.v1.OperatingMode" json:"desired_mode,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusResponse) Reset() {
	*x = GetSandboxStatusResponse{}
	mi := &file_v1_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusResponse) ProtoMessage() {}

func (x *GetSandboxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{6}
}

func (x *GetSandboxStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSandboxStatusResponse) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *GetSandboxStatusResponse) GetDesiredMode() OperatingMode {
	if x != nil {
		return x.DesiredMode
	}
	return OperatingMode_OPERATING_MODE_UNSPECIFIED
}

func (x *GetSandboxStatusResponse) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type RegisterRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TargetIp      string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRouteRequest) Reset() {
	*x = RegisterRouteRequest{}
	mi := &file_v1_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRouteRequest) ProtoMessage() {}

func (x *RegisterRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRouteRequest.ProtoReflect.Descriptor instead.
func (*RegisterRouteRequest) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRouteRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *RegisterRouteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterRouteRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *RegisterRouteRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

type RegisterRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    bool                   `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRouteResponse) Reset() {
	*x = RegisterRouteResponse{}
	mi := &file_v1_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRouteResponse) ProtoMessage() {}

func (x *RegisterRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRouteResponse.ProtoReflect.Descriptor instead.
func (*RegisterRouteResponse) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRouteResponse) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

type EvictRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictRouteRequest) Reset() {
	*x = EvictRouteRequest{}
	mi := &file_v1_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictRouteRequest) ProtoMessage() {}

func (x *EvictRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictRouteRequest.ProtoReflect.Descriptor instead.
func (*EvictRouteRequest) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{9}
}

func (x *EvictRouteRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *EvictRouteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type EvictRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evicted       bool                   `protobuf:"varint,1,opt,name=evicted,proto3" json:"evicted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictRouteResponse) Reset() {
	*x = EvictRouteResponse{}
	mi := &file_v1_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictRouteResponse) ProtoMessage() {}

func (x *EvictRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictRouteResponse.ProtoReflect.Descriptor instead.
func (*EvictRouteResponse) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{10}
}

func (x *EvictRouteResponse) GetEvicted() bool {
	if x != nil {
		return x.Evicted
	}
	return false
}

type GetIdleMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdleMetricsRequest) Reset() {
	*x = GetIdleMetricsRequest{}
	mi := &file_v1_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdleMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdleMetricsRequest) ProtoMessage() {}

func (x *GetIdleMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdleMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetIdleMetricsRequest) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{11}
}

func (x *GetIdleMetricsRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

type GetIdleMetricsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsIdle             bool                   `protobuf:"varint,1,opt,name=is_idle,json=isIdle,proto3" json:"is_idle,omitempty"`
	QueueSize          int32                  `protobuf:"varint,2,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	PendingReplies     int32                  `protobuf:"varint,3,opt,name=pending_replies,json=pendingReplies,proto3" json:"pending_replies,omitempty"`
	ActiveEmbeddedRuns int32                  `protobuf:"varint,4,opt,name=active_embedded_runs,json=activeEmbeddedRuns,proto3" json:"active_embedded_runs,omitempty"`
	ActiveTasks        int32                  `protobuf:"varint,5,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetIdleMetricsResponse) Reset() {
	*x = GetIdleMetricsResponse{}
	mi := &file_v1_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdleMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdleMetricsResponse) ProtoMessage() {}

func (x *GetIdleMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdleMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetIdleMetricsResponse) Descriptor() ([]byte, []int) {
	return file_v1_agents_proto_rawDescGZIP(), []int{12}
}

func (x *GetIdleMetricsResponse) GetIsIdle() bool {
	if x != nil {
		return x.IsIdle
	}
	return false
}

func (x *GetIdleMetricsResponse) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *GetIdleMetricsResponse) GetPendingReplies() int32 {
	if x != nil {
		return x.PendingReplies
	}
	return 0
}

func (x *GetIdleMetricsResponse) GetActiveEmbeddedRuns() int32 {
	if x != nil {
		return x.ActiveEmbeddedRuns
	}
	return 0
}

func (x *GetIdleMetricsResponse) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

var File_v1_agents_proto protoreflect.FileDescriptor

const file_v1_agents_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/agents.proto\x12\x15agents.integration.v1\"\xa2\x01\n" +
	"\x15SuspendSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0eforce_snapshot\x18\x03 \x01(\bR\rforceSnapshot\x120\n" +
	"\x14grace_period_seconds\x18\x04 \x01(\x03R\x12gracePeriodSeconds\"z\n" +
	"\x16SuspendSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fsnapshot_uid\x18\x02 \x01(\tR\vsnapshotUid\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x8f\x01\n" +
	"\x14ResumeSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\fsnapshot_uid\x18\x03 \x01(\tR\vsnapshotUid\x12\"\n" +
	"\rpre_warm_only\x18\x04 \x01(\bR\vpreWarmOnly\"m\n" +
	"\x15ResumeSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06pod_ip\x18\x02 \x01(\tR\x05podIp\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"K\n" +
	"\x17GetSandboxStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xab\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12@\n" +
	"\x1dlast_transition_time_epoch_ms\x18\x05 \x01(\x03R\x19lastTransitionTimeEpochMs\"\xf4\x01\n" +
	"\x18GetSandboxStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x05state\x18\x02 \x01(\x0e2#.agents.integration.v1.SandboxStateR\x05state\x12G\n" +
	"\fdesired_mode\x18\x03 \x01(\x0e2$.agents.integration.v1.OperatingModeR\vdesiredMode\x12@\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2 .agents.integration.v1.ConditionR\n" +
	"conditions\"\x95\x01\n" +
	"\x14RegisterRouteRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\"7\n" +
	"\x15RegisterRouteResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\bR\n" +
	"registered\"T\n" +
	"\x11EvictRouteRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\".\n" +
	"\x12EvictRouteResponse\x12\x18\n" +
	"\aevicted\x18\x01 \x01(\bR\aevicted\":\n" +
	"\x15GetIdleMetricsRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\"\xce\x01\n" +
	"\x16GetIdleMetricsResponse\x12\x17\n" +
	"\ais_idle\x18\x01 \x01(\bR\x06isIdle\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x02 \x01(\x05R\tqueueSize\x12'\n" +
	"\x0fpending_replies\x18\x03 \x01(\x05R\x0ependingReplies\x120\n" +
	"\x14active_embedded_runs\x18\x04 \x01(\x05R\x12activeEmbeddedRuns\x12!\n" +
	"\factive_tasks\x18\x05 \x01(\x05R\vactiveTasks*i\n" +
	"\rOperatingMode\x12\x1e\n" +
	"\x1aOPERATING_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OPERATING_MODE_RUNNING\x10\x01\x12\x1c\n" +
	"\x18OPERATING_MODE_SUSPENDED\x10\x02*\xbf\x01\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSANDBOX_STATE_PROVISIONING\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x02\x12\x1c\n" +
	"\x18SANDBOX_STATE_SUSPENDING\x10\x03\x12\x1b\n" +
	"\x17SANDBOX_STATE_SUSPENDED\x10\x04\x12\x1a\n" +
	"\x16SANDBOX_STATE_RESUMING\x10\x052\xe2\x02\n" +
	"\x10LifecycleService\x12m\n" +
	"\x0eSuspendSandbox\x12,.agents.integration.v1.SuspendSandboxRequest\x1a-.agents.integration.v1.SuspendSandboxResponse\x12j\n" +
	"\rResumeSandbox\x12+.agents.integration.v1.ResumeSandboxRequest\x1a,.agents.integration.v1.ResumeSandboxResponse\x12s\n" +
	"\x10GetSandboxStatus\x12..agents.integration.v1.GetSandboxStatusRequest\x1a/.agents.integration.v1.GetSandboxStatusResponse2\xdd\x01\n" +
	"\fProxyService\x12j\n" +
	"\rRegisterRoute\x12+.agents.integration.v1.RegisterRouteRequest\x1a,.agents.integration.v1.RegisterRouteResponse\x12a\n" +
	"\n" +
	"EvictRoute\x12(.agents.integration.v1.EvictRouteRequest\x1a).agents.integration.v1.EvictRouteResponse2}\n" +
	"\fScaleService\x12m\n" +
	"\x0eGetIdleMetrics\x12,.agents.integration.v1.GetIdleMetricsRequest\x1a-.agents.integration.v1.GetIdleMetricsResponseB-Z+sigs.k8s.io/agent-sandbox/plan/protos/v1;v1b\x06proto3"

var (
	file_v1_agents_proto_rawDescOnce sync.Once
	file_v1_agents_proto_rawDescData []byte
)

func file_v1_agents_proto_rawDescGZIP() []byte {
	file_v1_agents_proto_rawDescOnce.Do(func() {
		file_v1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agents_proto_rawDesc), len(file_v1_agents_proto_rawDesc)))
	})
	return file_v1_agents_proto_rawDescData
}

var file_v1_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_agents_proto_goTypes = []any{
	(OperatingMode)(0),               // 0: agents.integration.v1.OperatingMode
	(SandboxState)(0),                // 1: agents.integration.v1.SandboxState
	(*SuspendSandboxRequest)(nil),    // 2: agents.integration.v1.SuspendSandboxRequest
	(*SuspendSandboxResponse)(nil),   // 3: agents.integration.v1.SuspendSandboxResponse
	(*ResumeSandboxRequest)(nil),     // 4: agents.integration.v1.ResumeSandboxRequest
	(*ResumeSandboxResponse)(nil),    // 5: agents.integration.v1.ResumeSandboxResponse
	(*GetSandboxStatusRequest)(nil),  // 6: agents.integration.v1.GetSandboxStatusRequest
	(*Condition)(nil),                // 7: agents.integration.v1.Condition
	(*GetSandboxStatusResponse)(nil), // 8: agents.integration.v1.GetSandboxStatusResponse
	(*RegisterRouteRequest)(nil),     // 9: agents.integration.v1.RegisterRouteRequest
	(*RegisterRouteResponse)(nil),    // 10: agents.integration.v1.RegisterRouteResponse
	(*EvictRouteRequest)(nil),        // 11: agents.integration.v1.EvictRouteRequest
	(*EvictRouteResponse)(nil),       // 12: agents.integration.v1.EvictRouteResponse
	(*GetIdleMetricsRequest)(nil),    // 13: agents.integration.v1.GetIdleMetricsRequest
	(*GetIdleMetricsResponse)(nil),   // 14: agents.integration.v1.GetIdleMetricsResponse
}
var file_v1_agents_proto_depIdxs = []int32{
	1,  // 0: agents.integration.v1.GetSandboxStatusResponse.state:type_name -> agents.integration.v1.SandboxState
	0,  // 1: agents.integration.v1.GetSandboxStatusResponse.desired_mode:type_name -> agents.integration.v1.OperatingMode
	7,  // 2: agents.integration.v1.GetSandboxStatusResponse.conditions:type_name -> agents.integration.v1.Condition
	2,  // 3: agents.integration.v1.LifecycleService.SuspendSandbox:input_type -> agents.integration.v1.SuspendSandboxRequest
	4,  // 4: agents.integration.v1.LifecycleService.ResumeSandbox:input_type -> agents.integration.v1.ResumeSandboxRequest
	6,  // 5: agents.integration.v1.LifecycleService.GetSandboxStatus:input_type -> agents.integration.v1.GetSandboxStatusRequest
	9,  // 6: agents.integration.v1.ProxyService.RegisterRoute:input_type -> agents.integration.v1.RegisterRouteRequest
	11, // 7: agents.integration.v1.ProxyService.EvictRoute:input_type -> agents.integration.v1.EvictRouteRequest
	13, // 8: agents.integration.v1.ScaleService.GetIdleMetrics:input_type -> agents.integration.v1.GetIdleMetricsRequest
	3,  // 9: agents.integration.v1.LifecycleService.SuspendSandbox:output_type -> agents.integration.v1.SuspendSandboxResponse
	5,  // 10: agents.integration.v1.LifecycleService.ResumeSandbox:output_type -> agents.integration.v1.ResumeSandboxResponse
	8,  // 11: agents.integration.v1.LifecycleService.GetSandboxStatus:output_type -> agents.integration.v1.GetSandboxStatusResponse
	10, // 12: agents.integration.v1.ProxyService.RegisterRoute:output_type -> agents.integration.v1.RegisterRouteResponse
	12, // 13: agents.integration.v1.ProxyService.EvictRoute:output_type -> agents.integration.v1.EvictRouteResponse
	14, // 14: agents.integration.v1.ScaleService.GetIdleMetrics:output_type -> agents.integration.v1.GetIdleMetricsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_v1_agents_proto_init() }
func file_v1_agents_proto_init() {
	if File_v1_agents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agents_proto_rawDesc), len(file_v1_agents_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_v1_agents_proto_goTypes,
		DependencyIndexes: file_v1_agents_proto_depIdxs,
		EnumInfos:         file_v1_agents_proto_enumTypes,
		MessageInfos:      file_v1_agents_proto_msgTypes,
	}.Build()
	File_v1_agents_proto = out.File
	file_v1_agents_proto_goTypes = nil
	file_v1_agents_proto_depIdxs = nil
}
