// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/agents.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LifecycleService_SuspendSandbox_FullMethodName   = "/agents.integration.v1.LifecycleService/SuspendSandbox"
	LifecycleService_ResumeSandbox_FullMethodName    = "/agents.integration.v1.LifecycleService/ResumeSandbox"
	LifecycleService_GetSandboxStatus_FullMethodName = "/agents.integration.v1.LifecycleService/GetSandboxStatus"
)

// LifecycleServiceClient is the client API for LifecycleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------------------------------------------------
// Sandbox Lifecycle Service (Exposed by Sandbox Lifecycle Daemon)
// --------------------------------------------------------------------
type LifecycleServiceClient interface {
	// Triggers the scale-down/suspension of a Sandbox, including active CRIU checkpointing
	SuspendSandbox(ctx context.Context, in *SuspendSandboxRequest, opts ...grpc.CallOption) (*SuspendSandboxResponse, error)
	// Resumes a Sandbox, restoring process state from a warm pool snapshot
	ResumeSandbox(ctx context.Context, in *ResumeSandboxRequest, opts ...grpc.CallOption) (*ResumeSandboxResponse, error)
	// Queries the current status, state, and conditions of a Sandbox
	GetSandboxStatus(ctx context.Context, in *GetSandboxStatusRequest, opts ...grpc.CallOption) (*GetSandboxStatusResponse, error)
}

type lifecycleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLifecycleServiceClient(cc grpc.ClientConnInterface) LifecycleServiceClient {
	return &lifecycleServiceClient{cc}
}

func (c *lifecycleServiceClient) SuspendSandbox(ctx context.Context, in *SuspendSandboxRequest, opts ...grpc.CallOption) (*SuspendSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendSandboxResponse)
	err := c.cc.Invoke(ctx, LifecycleService_SuspendSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleServiceClient) ResumeSandbox(ctx context.Context, in *ResumeSandboxRequest, opts ...grpc.CallOption) (*ResumeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeSandboxResponse)
	err := c.cc.Invoke(ctx, LifecycleService_ResumeSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleServiceClient) GetSandboxStatus(ctx context.Context, in *GetSandboxStatusRequest, opts ...grpc.CallOption) (*GetSandboxStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxStatusResponse)
	err := c.cc.Invoke(ctx, LifecycleService_GetSandboxStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifecycleServiceServer is the server API for LifecycleService service.
// All implementations must embed UnimplementedLifecycleServiceServer
// for forward compatibility.
//
// --------------------------------------------------------------------
// Sandbox Lifecycle Service (Exposed by Sandbox Lifecycle Daemon)
// --------------------------------------------------------------------
type LifecycleServiceServer interface {
	// Triggers the scale-down/suspension of a Sandbox, including active CRIU checkpointing
	SuspendSandbox(context.Context, *SuspendSandboxRequest) (*SuspendSandboxResponse, error)
	// Resumes a Sandbox, restoring process state from a warm pool snapshot
	ResumeSandbox(context.Context, *ResumeSandboxRequest) (*ResumeSandboxResponse, error)
	// Queries the current status, state, and conditions of a Sandbox
	GetSandboxStatus(context.Context, *GetSandboxStatusRequest) (*GetSandboxStatusResponse, error)
	mustEmbedUnimplementedLifecycleServiceServer()
}

// UnimplementedLifecycleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLifecycleServiceServer struct{}

func (UnimplementedLifecycleServiceServer) SuspendSandbox(context.Context, *SuspendSandboxRequest) (*SuspendSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendSandbox not implemented")
}
func (UnimplementedLifecycleServiceServer) ResumeSandbox(context.Context, *ResumeSandboxRequest) (*ResumeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSandbox not implemented")
}
func (UnimplementedLifecycleServiceServer) GetSandboxStatus(context.Context, *GetSandboxStatusRequest) (*GetSandboxStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxStatus not implemented")
}
func (UnimplementedLifecycleServiceServer) mustEmbedUnimplementedLifecycleServiceServer() {}
func (UnimplementedLifecycleServiceServer) testEmbeddedByValue()                          {}

// UnsafeLifecycleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifecycleServiceServer will
// result in compilation errors.
type UnsafeLifecycleServiceServer interface {
	mustEmbedUnimplementedLifecycleServiceServer()
}

func RegisterLifecycleServiceServer(s grpc.ServiceRegistrar, srv LifecycleServiceServer) {
	// If the following call panics, it indicates UnimplementedLifecycleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LifecycleService_ServiceDesc, srv)
}

func _LifecycleService_SuspendSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).SuspendSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_SuspendSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).SuspendSandbox(ctx, req.(*SuspendSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifecycleService_ResumeSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).ResumeSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_ResumeSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).ResumeSandbox(ctx, req.(*ResumeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifecycleService_GetSandboxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).GetSandboxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_GetSandboxStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).GetSandboxStatus(ctx, req.(*GetSandboxStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LifecycleService_ServiceDesc is the grpc.ServiceDesc for LifecycleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifecycleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agents.integration.v1.LifecycleService",
	HandlerType: (*LifecycleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SuspendSandbox",
			Handler:    _LifecycleService_SuspendSandbox_Handler,
		},
		{
			MethodName: "ResumeSandbox",
			Handler:    _LifecycleService_ResumeSandbox_Handler,
		},
		{
			MethodName: "GetSandboxStatus",
			Handler:    _LifecycleService_GetSandboxStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/agents.proto",
}

const (
	ProxyService_RegisterRoute_FullMethodName = "/agents.integration.v1.ProxyService/RegisterRoute"
	ProxyService_EvictRoute_FullMethodName    = "/agents.integration.v1.ProxyService/EvictRoute"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------------------------------------------------
// Ingress Proxy Service (Exposed by Ingress/Traffic Broker)
// --------------------------------------------------------------------
type ProxyServiceClient interface {
	// Registers a dynamic routing endpoint for an active sandbox
	RegisterRoute(ctx context.Context, in *RegisterRouteRequest, opts ...grpc.CallOption) (*RegisterRouteResponse, error)
	// Evicts a route when a sandbox scales down
	EvictRoute(ctx context.Context, in *EvictRouteRequest, opts ...grpc.CallOption) (*EvictRouteResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) RegisterRoute(ctx context.Context, in *RegisterRouteRequest, opts ...grpc.CallOption) (*RegisterRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRouteResponse)
	err := c.cc.Invoke(ctx, ProxyService_RegisterRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) EvictRoute(ctx context.Context, in *EvictRouteRequest, opts ...grpc.CallOption) (*EvictRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictRouteResponse)
	err := c.cc.Invoke(ctx, ProxyService_EvictRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
//
// --------------------------------------------------------------------
// Ingress Proxy Service (Exposed by Ingress/Traffic Broker)
// --------------------------------------------------------------------
type ProxyServiceServer interface {
	// Registers a dynamic routing endpoint for an active sandbox
	RegisterRoute(context.Context, *RegisterRouteRequest) (*RegisterRouteResponse, error)
	// Evicts a route when a sandbox scales down
	EvictRoute(context.Context, *EvictRouteRequest) (*EvictRouteResponse, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) RegisterRoute(context.Context, *RegisterRouteRequest) (*RegisterRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRoute not implemented")
}
func (UnimplementedProxyServiceServer) EvictRoute(context.Context, *EvictRouteRequest) (*EvictRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvictRoute not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_RegisterRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).RegisterRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_RegisterRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).RegisterRoute(ctx, req.(*RegisterRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_EvictRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).EvictRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_EvictRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).EvictRoute(ctx, req.(*EvictRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agents.integration.v1.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRoute",
			Handler:    _ProxyService_RegisterRoute_Handler,
		},
		{
			MethodName: "EvictRoute",
			Handler:    _ProxyService_EvictRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/agents.proto",
}

const (
	ScaleService_GetIdleMetrics_FullMethodName = "/agents.integration.v1.ScaleService/GetIdleMetrics"
)

// ScaleServiceClient is the client API for ScaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------------------------------------------------
// OpenClaw Idle State Service (Exposed by OpenClaw Container/Scaling Agent)
// --------------------------------------------------------------------
type ScaleServiceClient interface {
	// Queries details on active queues, embedded runs, and idle status
	GetIdleMetrics(ctx context.Context, in *GetIdleMetricsRequest, opts ...grpc.CallOption) (*GetIdleMetricsResponse, error)
}

type scaleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScaleServiceClient(cc grpc.ClientConnInterface) ScaleServiceClient {
	return &scaleServiceClient{cc}
}

func (c *scaleServiceClient) GetIdleMetrics(ctx context.Context, in *GetIdleMetricsRequest, opts ...grpc.CallOption) (*GetIdleMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdleMetricsResponse)
	err := c.cc.Invoke(ctx, ScaleService_GetIdleMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScaleServiceServer is the server API for ScaleService service.
// All implementations must embed UnimplementedScaleServiceServer
// for forward compatibility.
//
// --------------------------------------------------------------------
// OpenClaw Idle State Service (Exposed by OpenClaw Container/Scaling Agent)
// --------------------------------------------------------------------
type ScaleServiceServer interface {
	// Queries details on active queues, embedded runs, and idle status
	GetIdleMetrics(context.Context, *GetIdleMetricsRequest) (*GetIdleMetricsResponse, error)
	mustEmbedUnimplementedScaleServiceServer()
}

// UnimplementedScaleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScaleServiceServer struct{}

func (UnimplementedScaleServiceServer) GetIdleMetrics(context.Context, *GetIdleMetricsRequest) (*GetIdleMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdleMetrics not implemented")
}
func (UnimplementedScaleServiceServer) mustEmbedUnimplementedScaleServiceServer() {}
func (UnimplementedScaleServiceServer) testEmbeddedByValue()                      {}

// UnsafeScaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScaleServiceServer will
// result in compilation errors.
type UnsafeScaleServiceServer interface {
	mustEmbedUnimplementedScaleServiceServer()
}

func RegisterScaleServiceServer(s grpc.ServiceRegistrar, srv ScaleServiceServer) {
	// If the following call panics, it indicates UnimplementedScaleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScaleService_ServiceDesc, srv)
}

func _ScaleService_GetIdleMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdleMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScaleServiceServer).GetIdleMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScaleService_GetIdleMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScaleServiceServer).GetIdleMetrics(ctx, req.(*GetIdleMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScaleService_ServiceDesc is the grpc.ServiceDesc for ScaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agents.integration.v1.ScaleService",
	HandlerType: (*ScaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdleMetrics",
			Handler:    _ScaleService_GetIdleMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/agents.proto",
}
