---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
  labels:
    app: agent-sandbox-controller
spec:
  serviceName: agent-sandbox-controller
  replicas: 1
  selector:
    matchLabels:
      app: agent-sandbox-controller
  template:
    metadata:
      labels:
        app: agent-sandbox-controller
    spec:
      serviceAccountName: agent-sandbox-controller
      containers:
      - name: agent-sandbox-controller
        image: us-central1-docker.pkg.dev/gke-ksiedlecki-hosted-master/agent-sandbox/agent-sandbox-controller:v20260224-tuned # Pointing to the new hosted location
        args:
        - "--extensions"
